import UserService from '../services/userService'

export class MockUserService extends UserService {
  constructor() {
    super(undefined)
  }

  async getUserRoles(_token: string) {
    return ['CELL_MOVE']
  }
}

export const mockApis = {
  prisonApi: {
    userLocations: undefined,
    userCaseLoads: undefined,
    setActiveCaseload: undefined,
    getHouseblockList: undefined,
    getActivityList: undefined,
    searchActivityLocations: undefined,
    getVisits: undefined,
    getVisitsForBookingWithVisitors: undefined,
    getVisitsSummary: undefined,
    getVisitsPrisons: undefined,
    getAppointments: undefined,
    getActivities: undefined,
    getPrisons: undefined,
    getAgencyDetails: undefined,
    getStaffDetails: undefined,
    getCourtEvents: undefined,
    getSentenceData: undefined,
    globalSearch: undefined,
    getExternalTransfers: undefined,
    getAlerts: undefined,
    getAlertsForBookingV2: undefined,
    getAlertsForLatestBooking: undefined,
    getAlertsSystem: undefined,
    getAssessments: undefined,
    getEstablishmentRollBlocksCount: undefined,
    getEstablishmentRollMovementsCount: undefined,
    getEstablishmentRollEnrouteCount: undefined,
    getInmates: undefined,
    getPrisonerImage: undefined,
    getLastPrison: undefined,
    getMovementsIn: undefined,
    getMovementsInBetween: undefined,
    getMovementsOut: undefined,
    getOffendersInReception: undefined,
    getRecentMovements: undefined,
    getDetails: undefined,
    getOffendersCurrentlyOutOfLivingUnit: undefined,
    getOffendersCurrentlyOutOfAgency: undefined,
    getLocation: undefined,
    getOffendersEnRoute: undefined,
    getBasicInmateDetailsForOffenders: undefined,
    getLocationsForAgency: undefined,
    getLocationsForAppointments: undefined,
    getAppointmentTypes: undefined,
    getAdjudicationFindingTypes: undefined,
    addAppointments: undefined,
    getAlertTypes: undefined,
    createAlert: undefined,
    getAlert: undefined,
    updateAlert: undefined,
    getOffenderSummaries: undefined,
    getOffenderSuspendedActivitiesOverDateRange: undefined,
    getActivitiesAtLocation: undefined,
    addSingleAppointment: undefined,
    getCaseNoteSummaryByTypes: undefined,
    getMainOffence: undefined,
    getStaffRoles: undefined,
    getPrisonerBalances: undefined,
    getPrisonerDetails: undefined,
    getPrisonerSentenceDetails: undefined,
    getPositiveCaseNotes: undefined,
    getNegativeCaseNotes: undefined,
    getPrisonerVisitBalances: undefined,
    getEventsForToday: undefined,
    getIdentifiers: undefined,
    getScheduledActivities: undefined,
    getOffenderAliases: undefined,
    getPhysicalAttributes: undefined,
    getPhysicalCharacteristics: undefined,
    getPhysicalMarks: undefined,
    getImage: undefined,
    getPrisonerProperty: undefined,
    getPrisonerDetail: undefined,
    getPrisonerContacts: undefined,
    getPersonAddresses: undefined,
    getPersonEmails: undefined,
    getPersonPhones: undefined,
    getProfileInformation: undefined,
    getPrisonerAddresses: undefined,
    getSecondaryLanguages: undefined,
    getPersonalCareNeeds: undefined,
    getReasonableAdjustments: undefined,
    getTreatmentTypes: undefined,
    getHealthTypes: undefined,
    getSentenceAdjustments: undefined,
    getCourtCases: undefined,
    getOffenceHistory: undefined,
    getSentenceTerms: undefined,
    getScheduledEventsForThisWeek: undefined,
    getScheduledEventsForNextWeek: undefined,
    getCellAttributes: undefined,
    getCellMoveReasonTypes: undefined,
    getCellsWithCapacity: undefined,
    getReceptionsWithCapacity: undefined,
    getCsraAssessments: undefined,
    getCsraAssessmentsForPrisoner: undefined,
    getCsraReviewForBooking: undefined,
    getOffenderCellHistory: undefined,
    getAttributesForLocation: undefined,
    getHistoryForLocation: undefined,
    getLocationDetails: undefined,
    getInmatesAtLocation: undefined,
    getInmatesAtLocationPrefix: undefined,
    moveToCellSwap: undefined,
    getOffenderDamageObligations: undefined,
    getTransactionHistory: undefined,
    getPrisoners: undefined,
    getUserDetailsList: undefined,
    getHistoryByDate: undefined,
    getOffenderActivitiesHistory: undefined,
    getMovementReasons: undefined,
    getTransfers: undefined,
    getVisitCompletionReasons: undefined,
    getVisitCancellationReasons: undefined,
  },
  systemOauthClient: {
    getClientCredentialsTokens: undefined,
  },
}

export const defaultServices = {
  apis: mockApis,
  userService: new MockUserService(),
}

export default {
  defaultServices,
  MockUserService,
  mockApis,
}
